const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT) || 587,
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

const sendCertificateEmail = async (toEmail, employeeName, pdfBuffer, certificateFileName) => {
  const mailOptions = {
    from: '"PSA Kalinga" <kalinga@psa.gov.ph>',
    to: toEmail,
    subject: 'Your Official PSA Certificate',
    text: `Dear ${employeeName},\n\nWe hope this email finds you well.\n\nAttached to this email is your requested official certificate from the Philippine Statistics Authority (PSA). This document has been verified and securely generated by our system.\n\nIf you have any questions or require further assistance regarding this document, please do not hesitate to contact our office.\n\nThank you for your continued service.\n\nBest regards,\n\nPhilippine Statistics Authority - Kalinga`,
    attachments: [
      {
        filename: certificateFileName,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  return await transporter.sendMail(mailOptions);
};

module.exports = {
  sendCertificateEmail,
};
